swiftmailer:
    url: '%env(MAILER_URL)%'
    spool: { type: 'memory' }
#  transport: smtp
#     auth_mode: login
#     port: 587
#     host: ssl0.ovh.net
#     username: sarrabdoulaye93@gmail.com
#     password: talesbokisarr22